### ISSUE TITLE
Microclima bugs and issues

### ISSUE THREAD

**Issue by RussellGrayxd** [ilyamaclean/microclima#12]
#########################################################
Please remove this note after reading it.

Thanks for taking the time to report an issue, please use the format below to submit your report. 
#########################################################

## Which operating system are you running?

[Windows 10]

## Which version of R are you using?

[R 3.6.3]

## What is the problem?

[Error in runauto() function after it hits the progress milestone "Downloading land sea data" with the following erro and warning messages:

Downscaling radiation and wind speed 
Calculating elevation and cold-air drainage effects 
Downloading land sea data 
Error in seq.default(from = ceiling(min_tile[2]), to = floor(max_tile[2])) : 
  'from' must be a finite number
In addition: Warning messages:
1: In microclima::microclimaforNMR(lat = longlat[2], long = longlat[1],  :
  Data sequence in UTC/GMT. Some or all dates using system timezone are in +07
2: In log(tan(lat_rad) + (1/cos(lat_rad))) : NaNs produced]

## How can we reproduce this? Which functions have you used and with which datasets and parameters?

[I used the runauto() function with a DEM raster input, and raster values for the habitat input between the dates "01/01/2020", and "01/06/2020". I don't know how you could reproduce this without my data.]

**Comment by RussellGrayxd** [comment]
When I change the daterange of the finish date to some earlier point its gets passed this error, and then runs an error when trying to open the netcdf files

Computing coastal exposure 
Direction: 0 degrees 
Direction: 45 degrees 
Direction: 90 degrees 
Direction: 135 degrees 
Direction: 180 degrees 
Direction: 225 degrees 
Direction: 270 degrees 
Direction: 315 degrees 
Computing mean coastal exposure of ncep grid cell 
Adjusting coastal exposure by ncep means 
Downloading sea-surface temperature data 
using cached file: C:\Users\Russe\AppData\Local\cache/R/noaa_ersst/201912.nc
date created (size, mb): 2020-08-06 19:24:22 (0.135)
using cached file: C:\Users\Russe\AppData\Local\cache/R/noaa_ersst/20201.nc
date created (size, mb): 2020-08-06 19:24:24 (0.135)
using cached file: C:\Users\Russe\AppData\Local\cache/R/noaa_ersst/20202.nc
date created (size, mb): 2020-08-06 19:24:27 (0.135)
using cached file: C:\Users\Russe\AppData\Local\cache/R/noaa_ersst/20203.nc
date created (size, mb): 2020-08-06 19:24:33 (0)
Error in R_nc4_open: NetCDF: Unknown file format
Error in ncdf4::nc_open(dpath) : 
  Error in nc_open trying to open file C:\Users\Russe\AppData\Local\cache/R/noaa_ersst/20203.nc

**Comment by everydayduffy** [comment]
Hi @RussellGrayxd , thanks for submitting an issue. This might be to do with unavailability of SST data from NOAA. Could you try running with `coastal = FALSE` and also try running for 2019, just to see if the problem persists?

**Comment by RussellGrayxd** [comment]
Hey James,
thanks for the quick reply. coastal = FALSE fixed the issue! 

Best regards,
-RG
--Russell J. Gray
Wildlife Ecology & Conservation Consultant
| 
0934581341 | rgrayherpetology@gmail.com
 |
| 
https://www.rjgrayecology.com/
 |
| 705 alligator ranch rd. New Smyrna Beach, FL, USA. 32168 |

 

    On Friday, August 7, 2020, 11:17:50 p.m. GMT+7, James P. Duffy <notifications@github.com> wrote:  
 
 


Hi @RussellGrayxd , thanks for submitting an issue. This might be to do with unavailability of SST data from NOAA. Could you try running with coastal = FALSE and also try running for 2019, just to see if the problem persists?
