### ISSUE TITLE
Micr issues

### ISSUE THREAD

**Issue by fipoucat** [ilyamaclean/microclima#23]
I am facing an error with microclima using micro_era5 and expect support to solve this:
 Accessing raster elevation [=========================] 100%
Mosaicing & Projecting
Note: Elevation units are in meters.
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.data.frame': could not find function "rungads"
In addition: Warning messages:
1: In if (class(hourlydata) == "logical") { :
  the condition has length > 1 and only the first element will be used
2: In .bvarsrem(bvars, boundary) : all basins flow into sea

Thanks

**Comment by ilyamaclean** [comment]
rangads is a function in NicheMapR, called by microclima, but not a package I maintain. Error best logged there

**Comment by ilyamaclean** [comment]
Warning message re: if (class(hourlydata) == "logical") issue now solved
