### ISSUE TITLE
Extracting multiple time series from runauto model output using xy coordinates 

### ISSUE THREAD

**Issue by EliseGallois** [ilyamaclean/microclima#24]
Hi there @ilyamaclean! I really love using microclima - it's such a nifty package. I've previously used the model output from runauto to look at microclimate variation across space, but I'm now trying to extract time series data from the output too. I have put in a range of dates into runauto and the model seems to run smoothly without error, but I'm having difficulties using raster::extract to pull out hourly meantemp time series data from a coordinates file with multiple xy GPS points. Is there functionality in the package for this that I have missed, or is this calling for some fancy looping? In any case, it'd be great if there was some functionality built in to support this if possible.

**Comment by ilyamaclean** [comment]
Hi Elise. The function runauto returns a list of objects, which in addition to rasters of tmean, tmax etc, includes, 'temps' an array of raw hourly values. If you convert that to a stacked raster or a terra::SpatRast using the input dem our output tmean as a template, it should be quite simple to do a time-series extract extract. E.g. 
library(raster)
require(NicheMapR)
# Run model for Pico, Azores
r <- get_dem(lat = 38.467429, long = -28.398995, resolution = 30)
temps <- runauto(r, "10/06/2010", "15/06/2010", hgt = 0.1, l = NA, x = NA,
                     habitat = "Barren or sparsely vegetated")
# Extract hourly data for two points
xy<-data.frame(x=c(-3161300,-3161800), y=c(4619100,4619800))
tc<-brick(temps$temps)
extent(tc)<-extent(r)
crs(tc)<-crs(r)
vs<-extract(tc,xy)

**Comment by EliseGallois** [comment]
Thank you so much! I was definitely overcomplicating things by making a loop here - the brick and extract process works perfectly and I now have a timeseries for multiple points, though had to convert from array to df first:

# convert to data frame
vs <- as.data.frame(vs)

# transpose
full_mean_ts <- t(vs) 
full_mean_ts <- tibble::rowid_to_column(full_mean_ts, "ID")

Thank you so much!
