### ISSUE TITLE
microclima will not install on R 

### ISSUE THREAD

**Issue by jflemi17** [ilyamaclean/microclima#28]
#########################################################
Please remove this note after reading it.

Thanks for taking the time to report an issue, please use the format below to submit your report. 
#########################################################

## Which operating system are you running?

MacOS 13.0

## Which version of R are you using?

I have tried the latest version 4.3.2 and 4.2.3

## What is the problem?

Microclima fails to install with the error: "GDALAllRegister not found in libgdal ERROR: configuration failed for package ‘rgdal’". After some searching it appears that the rgdal package has been retired. I have even tried manually installing with the source file with no luck. Can microclimate be updated to use the terra or the sf packages that serve similar functions as rgdal?

**Comment by GinjaFam** [comment]
You can install an archived rgdal version
remotes::install_url("https://cran.r-project.org/src/contrib/Archive/rgdal/rgdal_1.6-7.tar.gz", type="source")

**Comment by jflemi17** [comment]
Thank you! I was able to successfully install the archived version of rgdal. However, code that I was previously able to run using microclima is no longer running. Specifically, I am getting this error: 

dem <- microclima::get_dem(lat = lat, long = long, resolution = dem.res, xdims = 100, ydims = 100) ## lat and long values are numeric (-81.53,36.59)

**Error in st_transform.sfc(st_geometry(x), crs, ...) : 
  cannot transform sfc object with missing crs
In addition: Warning message:
In CPL_crs_from_input(x) :
  GDAL Error 1: PROJ: proj_create_from_database: Cannot find proj.db**


I came across this old post relating a similar issue to the order in which sf and rgdal are downloaded(https://stat.ethz.ch/pipermail/r-sig-geo/2020-September/028412.html). I tried uninstalling and reinstalling sf after rgdal to see if that was also the case here, but I get the same error. Any information is greatly appreciated.

**Comment by GinjaFam** [comment]
I was going mad with the installation until this morning. I was trying to do everything on my machine (macbook) and i was hitting a wall after another (especially fortran compiler). Then i decided to migrate the whole thing to the cloud (github codepace -  jupyter notebook with an R kernel).... and it all magically worked. It was really a lot of trial and error and i didn't encounter your specific error (didnt try the get_dem function).

**Comment by jflemi17** [comment]
Yes, even getting the archived version of rgdal to install involved several hurdles. Ended up wiping r and dependent compilers from my Mac and starting from scratch. After manually installing several dependencies I was able to get rgdal to install. It works for functions in the mcera5 package, so I am not sure why it won't work properly in microclima. I would really like to get things running locally, but for the time being I may need to give jupyter a try.

**Comment by dklinges9** [comment]
Hi folks,

Dave Klinges here, the maintainer of mcera5. The rgdal retirement has been causing a host of issues across the microclimate packages (and for many others). Although I can't directly address some of the underlying issues you discuss here on microclima's dependency on rgdal, you aren't alone in facing this.

I thought I should mention for those here (and future readers) that there is a development branch of the mcera5 package that has removed all dependencies on microclima, and therefore is not dependent on rgdal. Perhaps this might be of related use. You can see information on the mcera5 README:
https://github.com/dklinges9/mcera5

And install the dev branch:
remotes::install_github("dklinges9/mcera5", ref = "no_microclima")

**Comment by GinjaFam** [comment]
Thanks Dave and jflemi - happy to see i am not alone

**Comment by GinjaFam** [comment]
BTW: this really helped me to setup a virtual machine on the cloud. https://www.youtube.com/watch?v=ZUuPJOe2q1o

**Comment by ilyamaclean** [comment]
Solving this issue necessitated a comple overhaul of the microclima package to remove dependancies on rgdal and raster. This has now been implemented - everything uses terra and it shoudl install no problem
